### ISSUE TITLE
你好 用springsecurity还是shiro b站视频标题说是Security 但是看源码用的是shiro

### ISSUE THREAD

**Issue by carve-myself** [zykzhangyukang/Xinguan#3]

**Comment by zykzhangyukang** [comment]
我并没有说用的说springsecurity呀?用的说shiro&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zykzhangyukang/Xinguan"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月24日(星期一) 上午9:48
收件人:&nbsp;"zykzhangyukang/Xinguan"<Xinguan@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[zykzhangyukang/Xinguan] 你好 用springsecurity还是shiro b站视频标题说是Security 但是看源码用的是shiro (#3)
